---
name: "Hello World"
description: "This is a simple hello world action"

# dev branch change
on:
  push:
    branches:
      - main
      - dev

jobs:

  # job 1
  hello_world:
    name: Prints Hello World
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World from push"
