---
name: "scheduled actions"
description: "this runs based on the given schedule"

# workflow_dispatch, shows a manual 'Run Workflow' button that would trigger the event
# on: [push, workflow_dispatch]
on: [workflow_dispatch]
# on:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "*/1 * * * *"
  # workflow_dispatch:

jobs:

  # job 1
  show_me_time:
    runs-on: ubuntu-latest
    steps:
      - name: Five minute job that shows time
        run: echo "The current server time is $(date)"
